version: '3.8'

services:
  app:
    build: .
    ports:
      - '8001:8001'
    environment:
      - MONGODB_URI=mongodb+srv://aset:aset@bugg.ana11.mongodb.net/?retryWrites=true&w=majority&appName=Bugg
      - RABBITMQ_URL=amqps://epvsgzdz:4TyK1OUcgwa_PvR06dqJdvIroiLcPQ48@moose.rmq.cloudamqp.com/epvsgzdz
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - rabbitmq
      - redis

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672' 
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
